// Stub for the runtime-only Pagefind bundle (`/pagefind/pagefind.js`), which is
// generated by the `pagefind` postbuild step and therefore does not exist during
// unit tests. The Search component loads it lazily and gracefully falls back when
// it is unavailable, so an empty module is sufficient for the test environment.
export {};
