{{- if and .Values.ingress.enabled (not .Values.ingress.traefikCRD) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "open-git.fullname" . }}
  labels:
    {{- include "open-git.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "open-git.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "open-git.fullname" . }}-backend
                port:
                  number: {{ .Values.service.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "open-git.fullname" . }}-frontend
                port:
                  number: {{ .Values.service.frontend.port }}
{{- end }}
