ALTER TABLE users ADD COLUMN name TEXT;
ALTER TABLE users ADD COLUMN bio TEXT;
ALTER TABLE users ADD COLUMN avatar_url TEXT;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE access_tokens ADD COLUMN note TEXT;
ALTER TABLE access_tokens ADD COLUMN last_used_at TIMESTAMP;
