ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_address TEXT;
CREATE TABLE IF NOT EXISTS system_settings (key TEXT PRIMARY KEY, value JSONB, updated_by UUID REFERENCES users(id) ON DELETE SET NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
