// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Actor interface {
	IsActor()
	GetLogin() string
	GetAvatarURL() string
	GetURL() string
}

type Labelable interface {
	IsLabelable()
	GetID() string
	GetLabels() *LabelConnection
}

type Node interface {
	IsNode()
	GetID() string
}

type RepositoryOwner interface {
	IsRepositoryOwner()
}

type AddCommentInput struct {
	SubjectID        string  `json:"subjectId"`
	Body             string  `json:"body"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type AddCommentPayload struct {
	CommentEdge      *IssueCommentEdge `json:"commentEdge,omitempty"`
	Comment          *IssueComment     `json:"comment,omitempty"`
	Subject          Node              `json:"subject,omitempty"`
	ClientMutationID *string           `json:"clientMutationId,omitempty"`
}

type AddLabelsToLabelableInput struct {
	LabelableID      string   `json:"labelableId"`
	LabelIds         []string `json:"labelIds"`
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
}

type AddLabelsToLabelablePayload struct {
	Labelable        Labelable `json:"labelable,omitempty"`
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
}

type CloseIssueInput struct {
	IssueID          string  `json:"issueId"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type CloseIssuePayload struct {
	Issue            *Issue  `json:"issue,omitempty"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type ClosePullRequestInput struct {
	PullRequestID    string  `json:"pullRequestId"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type ClosePullRequestPayload struct {
	PullRequest      *PullRequest `json:"pullRequest,omitempty"`
	ClientMutationID *string      `json:"clientMutationId,omitempty"`
}

type CreateIssueInput struct {
	RepositoryID     string   `json:"repositoryId"`
	Title            string   `json:"title"`
	Body             *string  `json:"body,omitempty"`
	LabelIds         []string `json:"labelIds,omitempty"`
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
}

type CreateIssuePayload struct {
	Issue            *Issue  `json:"issue,omitempty"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type CreatePullRequestInput struct {
	RepositoryID     string  `json:"repositoryId"`
	Title            string  `json:"title"`
	Body             *string `json:"body,omitempty"`
	HeadRefName      string  `json:"headRefName"`
	BaseRefName      string  `json:"baseRefName"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type CreatePullRequestPayload struct {
	PullRequest      *PullRequest `json:"pullRequest,omitempty"`
	ClientMutationID *string      `json:"clientMutationId,omitempty"`
}

type Issue struct {
	ID         string                  `json:"id"`
	Number     int                     `json:"number"`
	Title      string                  `json:"title"`
	Body       *string                 `json:"body,omitempty"`
	State      IssueState              `json:"state"`
	Author     Actor                   `json:"author,omitempty"`
	Repository *Repository             `json:"repository"`
	Labels     *LabelConnection        `json:"labels"`
	Comments   *IssueCommentConnection `json:"comments"`
	Milestone  *Milestone              `json:"milestone,omitempty"`
	CreatedAt  string                  `json:"createdAt"`
	UpdatedAt  string                  `json:"updatedAt"`
	ClosedAt   *string                 `json:"closedAt,omitempty"`
}

func (Issue) IsNode()            {}
func (this Issue) GetID() string { return this.ID }

func (Issue) IsLabelable() {}

func (this Issue) GetLabels() *LabelConnection { return this.Labels }

type IssueComment struct {
	ID        string `json:"id"`
	Body      string `json:"body"`
	Author    Actor  `json:"author,omitempty"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

func (IssueComment) IsNode()            {}
func (this IssueComment) GetID() string { return this.ID }

type IssueCommentConnection struct {
	Edges      []*IssueCommentEdge `json:"edges,omitempty"`
	Nodes      []*IssueComment     `json:"nodes,omitempty"`
	PageInfo   *PageInfo           `json:"pageInfo"`
	TotalCount int                 `json:"totalCount"`
}

type IssueCommentEdge struct {
	Cursor string        `json:"cursor"`
	Node   *IssueComment `json:"node"`
}

type IssueConnection struct {
	Edges      []*IssueEdge `json:"edges,omitempty"`
	Nodes      []*Issue     `json:"nodes,omitempty"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type IssueEdge struct {
	Cursor string `json:"cursor"`
	Node   *Issue `json:"node"`
}

type Label struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Color       string  `json:"color"`
	Description *string `json:"description,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

func (Label) IsNode()            {}
func (this Label) GetID() string { return this.ID }

type LabelConnection struct {
	Edges      []*LabelEdge `json:"edges,omitempty"`
	Nodes      []*Label     `json:"nodes,omitempty"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type LabelEdge struct {
	Cursor string `json:"cursor"`
	Node   *Label `json:"node"`
}

type MergePullRequestInput struct {
	PullRequestID    string                  `json:"pullRequestId"`
	CommitHeadline   *string                 `json:"commitHeadline,omitempty"`
	MergeMethod      *PullRequestMergeMethod `json:"mergeMethod,omitempty"`
	ClientMutationID *string                 `json:"clientMutationId,omitempty"`
}

type MergePullRequestPayload struct {
	PullRequest      *PullRequest `json:"pullRequest,omitempty"`
	ClientMutationID *string      `json:"clientMutationId,omitempty"`
}

type Milestone struct {
	ID          string         `json:"id"`
	Number      int            `json:"number"`
	Title       string         `json:"title"`
	Description *string        `json:"description,omitempty"`
	State       MilestoneState `json:"state"`
	DueOn       *string        `json:"dueOn,omitempty"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
	ClosedAt    *string        `json:"closedAt,omitempty"`
}

func (Milestone) IsNode()            {}
func (this Milestone) GetID() string { return this.ID }

type MilestoneConnection struct {
	Edges      []*MilestoneEdge `json:"edges,omitempty"`
	Nodes      []*Milestone     `json:"nodes,omitempty"`
	PageInfo   *PageInfo        `json:"pageInfo"`
	TotalCount int              `json:"totalCount"`
}

type MilestoneEdge struct {
	Cursor string     `json:"cursor"`
	Node   *Milestone `json:"node"`
}

type Mutation struct {
}

type Organization struct {
	ID          string  `json:"id"`
	Login       string  `json:"login"`
	Name        *string `json:"name,omitempty"`
	URL         string  `json:"url"`
	AvatarURL   string  `json:"avatarUrl"`
	Description *string `json:"description,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

func (Organization) IsRepositoryOwner() {}

func (Organization) IsNode()            {}
func (this Organization) GetID() string { return this.ID }

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PullRequest struct {
	ID             string                  `json:"id"`
	Number         int                     `json:"number"`
	Title          string                  `json:"title"`
	Body           *string                 `json:"body,omitempty"`
	State          PullRequestState        `json:"state"`
	Author         Actor                   `json:"author,omitempty"`
	Repository     *Repository             `json:"repository"`
	HeadRefName    string                  `json:"headRefName"`
	BaseRefName    string                  `json:"baseRefName"`
	Mergeable      MergeableState          `json:"mergeable"`
	MergeableState MergeableState          `json:"mergeableState"`
	Labels         *LabelConnection        `json:"labels"`
	Comments       *IssueCommentConnection `json:"comments"`
	CreatedAt      string                  `json:"createdAt"`
	UpdatedAt      string                  `json:"updatedAt"`
	ClosedAt       *string                 `json:"closedAt,omitempty"`
	MergedAt       *string                 `json:"mergedAt,omitempty"`
}

func (PullRequest) IsNode()            {}
func (this PullRequest) GetID() string { return this.ID }

func (PullRequest) IsLabelable() {}

func (this PullRequest) GetLabels() *LabelConnection { return this.Labels }

type PullRequestConnection struct {
	Edges      []*PullRequestEdge `json:"edges,omitempty"`
	Nodes      []*PullRequest     `json:"nodes,omitempty"`
	PageInfo   *PageInfo          `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

type PullRequestEdge struct {
	Cursor string       `json:"cursor"`
	Node   *PullRequest `json:"node"`
}

type Query struct {
}

type RemoveLabelsFromLabelableInput struct {
	LabelableID      string   `json:"labelableId"`
	LabelIds         []string `json:"labelIds"`
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
}

type RemoveLabelsFromLabelablePayload struct {
	Labelable        Labelable `json:"labelable,omitempty"`
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
}

type ReopenIssueInput struct {
	IssueID          string  `json:"issueId"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type ReopenIssuePayload struct {
	Issue            *Issue  `json:"issue,omitempty"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type Repository struct {
	ID            string                 `json:"id"`
	Name          string                 `json:"name"`
	NameWithOwner string                 `json:"nameWithOwner"`
	URL           string                 `json:"url"`
	Description   *string                `json:"description,omitempty"`
	IsPrivate     bool                   `json:"isPrivate"`
	Owner         RepositoryOwner        `json:"owner"`
	CreatedAt     string                 `json:"createdAt"`
	UpdatedAt     string                 `json:"updatedAt"`
	Issue         *Issue                 `json:"issue,omitempty"`
	Issues        *IssueConnection       `json:"issues"`
	PullRequest   *PullRequest           `json:"pullRequest,omitempty"`
	PullRequests  *PullRequestConnection `json:"pullRequests"`
	Labels        *LabelConnection       `json:"labels"`
	Milestones    *MilestoneConnection   `json:"milestones"`
}

func (Repository) IsNode()            {}
func (this Repository) GetID() string { return this.ID }

type UpdateIssueInput struct {
	ID               string      `json:"id"`
	Title            *string     `json:"title,omitempty"`
	Body             *string     `json:"body,omitempty"`
	State            *IssueState `json:"state,omitempty"`
	LabelIds         []string    `json:"labelIds,omitempty"`
	ClientMutationID *string     `json:"clientMutationId,omitempty"`
}

type UpdateIssuePayload struct {
	Issue            *Issue  `json:"issue,omitempty"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Login     string  `json:"login"`
	AvatarURL string  `json:"avatarUrl"`
	URL       string  `json:"url"`
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	Bio       *string `json:"bio,omitempty"`
	Company   *string `json:"company,omitempty"`
	Location  *string `json:"location,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

func (User) IsRepositoryOwner() {}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }

func (User) IsActor()                  {}
func (this User) GetLogin() string     { return this.Login }
func (this User) GetAvatarURL() string { return this.AvatarURL }
func (this User) GetURL() string       { return this.URL }

type IssueState string

const (
	IssueStateOpen   IssueState = "OPEN"
	IssueStateClosed IssueState = "CLOSED"
)

var AllIssueState = []IssueState{
	IssueStateOpen,
	IssueStateClosed,
}

func (e IssueState) IsValid() bool {
	switch e {
	case IssueStateOpen, IssueStateClosed:
		return true
	}
	return false
}

func (e IssueState) String() string {
	return string(e)
}

func (e *IssueState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IssueState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IssueState", str)
	}
	return nil
}

func (e IssueState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MergeableState string

const (
	MergeableStateMergeable   MergeableState = "MERGEABLE"
	MergeableStateConflicting MergeableState = "CONFLICTING"
	MergeableStateUnknown     MergeableState = "UNKNOWN"
)

var AllMergeableState = []MergeableState{
	MergeableStateMergeable,
	MergeableStateConflicting,
	MergeableStateUnknown,
}

func (e MergeableState) IsValid() bool {
	switch e {
	case MergeableStateMergeable, MergeableStateConflicting, MergeableStateUnknown:
		return true
	}
	return false
}

func (e MergeableState) String() string {
	return string(e)
}

func (e *MergeableState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MergeableState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MergeableState", str)
	}
	return nil
}

func (e MergeableState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MilestoneState string

const (
	MilestoneStateOpen   MilestoneState = "OPEN"
	MilestoneStateClosed MilestoneState = "CLOSED"
)

var AllMilestoneState = []MilestoneState{
	MilestoneStateOpen,
	MilestoneStateClosed,
}

func (e MilestoneState) IsValid() bool {
	switch e {
	case MilestoneStateOpen, MilestoneStateClosed:
		return true
	}
	return false
}

func (e MilestoneState) String() string {
	return string(e)
}

func (e *MilestoneState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MilestoneState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MilestoneState", str)
	}
	return nil
}

func (e MilestoneState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PullRequestMergeMethod string

const (
	PullRequestMergeMethodMerge  PullRequestMergeMethod = "MERGE"
	PullRequestMergeMethodSquash PullRequestMergeMethod = "SQUASH"
	PullRequestMergeMethodRebase PullRequestMergeMethod = "REBASE"
)

var AllPullRequestMergeMethod = []PullRequestMergeMethod{
	PullRequestMergeMethodMerge,
	PullRequestMergeMethodSquash,
	PullRequestMergeMethodRebase,
}

func (e PullRequestMergeMethod) IsValid() bool {
	switch e {
	case PullRequestMergeMethodMerge, PullRequestMergeMethodSquash, PullRequestMergeMethodRebase:
		return true
	}
	return false
}

func (e PullRequestMergeMethod) String() string {
	return string(e)
}

func (e *PullRequestMergeMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PullRequestMergeMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PullRequestMergeMethod", str)
	}
	return nil
}

func (e PullRequestMergeMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PullRequestState string

const (
	PullRequestStateOpen   PullRequestState = "OPEN"
	PullRequestStateClosed PullRequestState = "CLOSED"
	PullRequestStateMerged PullRequestState = "MERGED"
)

var AllPullRequestState = []PullRequestState{
	PullRequestStateOpen,
	PullRequestStateClosed,
	PullRequestStateMerged,
}

func (e PullRequestState) IsValid() bool {
	switch e {
	case PullRequestStateOpen, PullRequestStateClosed, PullRequestStateMerged:
		return true
	}
	return false
}

func (e PullRequestState) String() string {
	return string(e)
}

func (e *PullRequestState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PullRequestState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PullRequestState", str)
	}
	return nil
}

func (e PullRequestState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
